name: Post tweet

on: push
#   schedule:
#   - cron: "30 */6 * * *"

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}



jobs:
  post-tweet:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run:
          pip install --upgrade pip
          pip install requeriments

      - name: Run script 
        run:
          python main.py

